/*
 * generated by Xtext 2.21.0
 */
package wizard.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WizardUiModule extends AbstractWizardUiModule {

	public WizardUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
