/*
 * generated by Xtext 2.21.0
 */
package wizard.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import wizard.xtext.ui.internal.XtextActivator;

public class WizardUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("wizard.Wizard");
	}

}
