/*
 * generated by Xtext 2.21.0
 */
package wizard;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WizardRuntimeModule extends AbstractWizardRuntimeModule {
}
