/*
 * generated by Xtext 2.21.0
 */
package wizard.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class WizardGrammarAccess extends AbstractGrammarElementFinder {
	
	public class WizardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Wizard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWizardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTituloAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTituloEStringParserRuleCall_1_0 = (RuleCall)cTituloAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPaginasAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPaginasPaginaParserRuleCall_3_0 = (RuleCall)cPaginasAssignment_3.eContents().get(0);
		private final Assignment cPaginasAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPaginasPaginaParserRuleCall_4_0 = (RuleCall)cPaginasAssignment_4.eContents().get(0);
		
		//Wizard:
		//	'Wizard' titulo=EString ':'
		//	paginas+=Pagina paginas+=Pagina*;
		@Override public ParserRule getRule() { return rule; }
		
		//'Wizard' titulo=EString ':' paginas+=Pagina paginas+=Pagina*
		public Group getGroup() { return cGroup; }
		
		//'Wizard'
		public Keyword getWizardKeyword_0() { return cWizardKeyword_0; }
		
		//titulo=EString
		public Assignment getTituloAssignment_1() { return cTituloAssignment_1; }
		
		//EString
		public RuleCall getTituloEStringParserRuleCall_1_0() { return cTituloEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//paginas+=Pagina
		public Assignment getPaginasAssignment_3() { return cPaginasAssignment_3; }
		
		//Pagina
		public RuleCall getPaginasPaginaParserRuleCall_3_0() { return cPaginasPaginaParserRuleCall_3_0; }
		
		//paginas+=Pagina*
		public Assignment getPaginasAssignment_4() { return cPaginasAssignment_4; }
		
		//Pagina
		public RuleCall getPaginasPaginaParserRuleCall_4_0() { return cPaginasPaginaParserRuleCall_4_0; }
	}
	public class BotonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Boton");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNavegarParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMostrarParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCerrarParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Boton:
		//	Navegar | Mostrar | Cerrar;
		@Override public ParserRule getRule() { return rule; }
		
		//Navegar | Mostrar | Cerrar
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Navegar
		public RuleCall getNavegarParserRuleCall_0() { return cNavegarParserRuleCall_0; }
		
		//Mostrar
		public RuleCall getMostrarParserRuleCall_1() { return cMostrarParserRuleCall_1; }
		
		//Cerrar
		public RuleCall getCerrarParserRuleCall_2() { return cCerrarParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class PaginaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Pagina");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPaginaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Assignment cInicialAssignment_1_0_0 = (Assignment)cGroup_1_0.eContents().get(0);
		private final Keyword cInicialInicialKeyword_1_0_0_0 = (Keyword)cInicialAssignment_1_0_0.eContents().get(0);
		private final Assignment cNameAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0_1_0 = (RuleCall)cNameAssignment_1_0_1.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cGroup_3.eContents().get(0);
		private final Assignment cCamposAssignment_3_0_0 = (Assignment)cGroup_3_0.eContents().get(0);
		private final RuleCall cCamposCampoParserRuleCall_3_0_0_0 = (RuleCall)cCamposAssignment_3_0_0.eContents().get(0);
		private final Assignment cCamposAssignment_3_0_1 = (Assignment)cGroup_3_0.eContents().get(1);
		private final RuleCall cCamposCampoParserRuleCall_3_0_1_0 = (RuleCall)cCamposAssignment_3_0_1.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Assignment cCasillasAssignment_3_1_0 = (Assignment)cGroup_3_1.eContents().get(0);
		private final RuleCall cCasillasCasillaParserRuleCall_3_1_0_0 = (RuleCall)cCasillasAssignment_3_1_0.eContents().get(0);
		private final Assignment cCasillasAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cCasillasCasillaParserRuleCall_3_1_1_0 = (RuleCall)cCasillasAssignment_3_1_1.eContents().get(0);
		private final Assignment cBotonesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cBotonesBotonParserRuleCall_3_2_0 = (RuleCall)cBotonesAssignment_3_2.eContents().get(0);
		private final Assignment cBotonesAssignment_3_3 = (Assignment)cGroup_3.eContents().get(3);
		private final RuleCall cBotonesBotonParserRuleCall_3_3_0 = (RuleCall)cBotonesAssignment_3_3.eContents().get(0);
		
		//Pagina:
		//	'Pagina' (inicial?='inicial' name=EString | name=EString) ':' ((campos+=Campo campos+=Campo*)? (casillas+=Casilla
		//	casillas+=Casilla*)? botones+=Boton botones+=Boton*);
		@Override public ParserRule getRule() { return rule; }
		
		//'Pagina' (inicial?='inicial' name=EString | name=EString) ':' ((campos+=Campo campos+=Campo*)? (casillas+=Casilla
		//casillas+=Casilla*)? botones+=Boton botones+=Boton*)
		public Group getGroup() { return cGroup; }
		
		//'Pagina'
		public Keyword getPaginaKeyword_0() { return cPaginaKeyword_0; }
		
		//(inicial?='inicial' name=EString | name=EString)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//inicial?='inicial' name=EString
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//inicial?='inicial'
		public Assignment getInicialAssignment_1_0_0() { return cInicialAssignment_1_0_0; }
		
		//'inicial'
		public Keyword getInicialInicialKeyword_1_0_0_0() { return cInicialInicialKeyword_1_0_0_0; }
		
		//name=EString
		public Assignment getNameAssignment_1_0_1() { return cNameAssignment_1_0_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0_1_0() { return cNameEStringParserRuleCall_1_0_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_1_0() { return cNameEStringParserRuleCall_1_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//((campos+=Campo campos+=Campo*)? (casillas+=Casilla casillas+=Casilla*)? botones+=Boton botones+=Boton*)
		public Group getGroup_3() { return cGroup_3; }
		
		//(campos+=Campo campos+=Campo*)?
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//campos+=Campo
		public Assignment getCamposAssignment_3_0_0() { return cCamposAssignment_3_0_0; }
		
		//Campo
		public RuleCall getCamposCampoParserRuleCall_3_0_0_0() { return cCamposCampoParserRuleCall_3_0_0_0; }
		
		//campos+=Campo*
		public Assignment getCamposAssignment_3_0_1() { return cCamposAssignment_3_0_1; }
		
		//Campo
		public RuleCall getCamposCampoParserRuleCall_3_0_1_0() { return cCamposCampoParserRuleCall_3_0_1_0; }
		
		//(casillas+=Casilla casillas+=Casilla*)?
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//casillas+=Casilla
		public Assignment getCasillasAssignment_3_1_0() { return cCasillasAssignment_3_1_0; }
		
		//Casilla
		public RuleCall getCasillasCasillaParserRuleCall_3_1_0_0() { return cCasillasCasillaParserRuleCall_3_1_0_0; }
		
		//casillas+=Casilla*
		public Assignment getCasillasAssignment_3_1_1() { return cCasillasAssignment_3_1_1; }
		
		//Casilla
		public RuleCall getCasillasCasillaParserRuleCall_3_1_1_0() { return cCasillasCasillaParserRuleCall_3_1_1_0; }
		
		//botones+=Boton
		public Assignment getBotonesAssignment_3_2() { return cBotonesAssignment_3_2; }
		
		//Boton
		public RuleCall getBotonesBotonParserRuleCall_3_2_0() { return cBotonesBotonParserRuleCall_3_2_0; }
		
		//botones+=Boton*
		public Assignment getBotonesAssignment_3_3() { return cBotonesAssignment_3_3; }
		
		//Boton
		public RuleCall getBotonesBotonParserRuleCall_3_3_0() { return cBotonesBotonParserRuleCall_3_3_0; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class CampoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Campo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCampoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cObligatorioAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cObligatorioObligatorioKeyword_1_0 = (Keyword)cObligatorioAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEtiquetaAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEtiquetaEStringParserRuleCall_3_0 = (RuleCall)cEtiquetaAssignment_3.eContents().get(0);
		
		//Campo:
		//	'Campo' obligatorio?='obligatorio'? ':' etiqueta=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'Campo' obligatorio?='obligatorio'? ':' etiqueta=EString
		public Group getGroup() { return cGroup; }
		
		//'Campo'
		public Keyword getCampoKeyword_0() { return cCampoKeyword_0; }
		
		//obligatorio?='obligatorio'?
		public Assignment getObligatorioAssignment_1() { return cObligatorioAssignment_1; }
		
		//'obligatorio'
		public Keyword getObligatorioObligatorioKeyword_1_0() { return cObligatorioObligatorioKeyword_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//etiqueta=EString
		public Assignment getEtiquetaAssignment_3() { return cEtiquetaAssignment_3; }
		
		//EString
		public RuleCall getEtiquetaEStringParserRuleCall_3_0() { return cEtiquetaEStringParserRuleCall_3_0; }
	}
	public class CasillaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Casilla");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCasillaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSeleccionadoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cSeleccionadoSeleccionadaKeyword_1_0 = (Keyword)cSeleccionadoAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEtiquetaAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEtiquetaEStringParserRuleCall_4_0 = (RuleCall)cEtiquetaAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDestinoKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cNuevoDestinoAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cNuevoDestinoPaginaCrossReference_5_1_0 = (CrossReference)cNuevoDestinoAssignment_5_1.eContents().get(0);
		private final RuleCall cNuevoDestinoPaginaEStringParserRuleCall_5_1_0_1 = (RuleCall)cNuevoDestinoPaginaCrossReference_5_1_0.eContents().get(1);
		
		//Casilla:
		//	'Casilla' seleccionado?='seleccionada'? name=EString ':' etiqueta=EString ('destino' nuevoDestino=[Pagina|EString])?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Casilla' seleccionado?='seleccionada'? name=EString ':' etiqueta=EString ('destino' nuevoDestino=[Pagina|EString])?
		public Group getGroup() { return cGroup; }
		
		//'Casilla'
		public Keyword getCasillaKeyword_0() { return cCasillaKeyword_0; }
		
		//seleccionado?='seleccionada'?
		public Assignment getSeleccionadoAssignment_1() { return cSeleccionadoAssignment_1; }
		
		//'seleccionada'
		public Keyword getSeleccionadoSeleccionadaKeyword_1_0() { return cSeleccionadoSeleccionadaKeyword_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//etiqueta=EString
		public Assignment getEtiquetaAssignment_4() { return cEtiquetaAssignment_4; }
		
		//EString
		public RuleCall getEtiquetaEStringParserRuleCall_4_0() { return cEtiquetaEStringParserRuleCall_4_0; }
		
		//('destino' nuevoDestino=[Pagina|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'destino'
		public Keyword getDestinoKeyword_5_0() { return cDestinoKeyword_5_0; }
		
		//nuevoDestino=[Pagina|EString]
		public Assignment getNuevoDestinoAssignment_5_1() { return cNuevoDestinoAssignment_5_1; }
		
		//[Pagina|EString]
		public CrossReference getNuevoDestinoPaginaCrossReference_5_1_0() { return cNuevoDestinoPaginaCrossReference_5_1_0; }
		
		//EString
		public RuleCall getNuevoDestinoPaginaEStringParserRuleCall_5_1_0_1() { return cNuevoDestinoPaginaEStringParserRuleCall_5_1_0_1; }
	}
	public class NavegarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Navegar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNavegarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEtiquetaAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEtiquetaEStringParserRuleCall_2_0 = (RuleCall)cEtiquetaAssignment_2.eContents().get(0);
		private final Assignment cDestinoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cDestinoPaginaCrossReference_3_0 = (CrossReference)cDestinoAssignment_3.eContents().get(0);
		private final RuleCall cDestinoPaginaEStringParserRuleCall_3_0_1 = (RuleCall)cDestinoPaginaCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDependenciasKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cCasillasAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cCasillasCasillaCrossReference_4_2_0 = (CrossReference)cCasillasAssignment_4_2.eContents().get(0);
		private final RuleCall cCasillasCasillaEStringParserRuleCall_4_2_0_1 = (RuleCall)cCasillasCasillaCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cCasillasAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cCasillasCasillaCrossReference_4_3_1_0 = (CrossReference)cCasillasAssignment_4_3_1.eContents().get(0);
		private final RuleCall cCasillasCasillaEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cCasillasCasillaCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		
		//Navegar:
		//	'Navegar' ':' etiqueta=EString destino=[Pagina|EString] ('dependencias' '{' casillas+=[Casilla|EString] (','
		//	casillas+=[Casilla|EString])* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Navegar' ':' etiqueta=EString destino=[Pagina|EString] ('dependencias' '{' casillas+=[Casilla|EString] (','
		//casillas+=[Casilla|EString])* '}')?
		public Group getGroup() { return cGroup; }
		
		//'Navegar'
		public Keyword getNavegarKeyword_0() { return cNavegarKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//etiqueta=EString
		public Assignment getEtiquetaAssignment_2() { return cEtiquetaAssignment_2; }
		
		//EString
		public RuleCall getEtiquetaEStringParserRuleCall_2_0() { return cEtiquetaEStringParserRuleCall_2_0; }
		
		//destino=[Pagina|EString]
		public Assignment getDestinoAssignment_3() { return cDestinoAssignment_3; }
		
		//[Pagina|EString]
		public CrossReference getDestinoPaginaCrossReference_3_0() { return cDestinoPaginaCrossReference_3_0; }
		
		//EString
		public RuleCall getDestinoPaginaEStringParserRuleCall_3_0_1() { return cDestinoPaginaEStringParserRuleCall_3_0_1; }
		
		//('dependencias' '{' casillas+=[Casilla|EString] (',' casillas+=[Casilla|EString])* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'dependencias'
		public Keyword getDependenciasKeyword_4_0() { return cDependenciasKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//casillas+=[Casilla|EString]
		public Assignment getCasillasAssignment_4_2() { return cCasillasAssignment_4_2; }
		
		//[Casilla|EString]
		public CrossReference getCasillasCasillaCrossReference_4_2_0() { return cCasillasCasillaCrossReference_4_2_0; }
		
		//EString
		public RuleCall getCasillasCasillaEStringParserRuleCall_4_2_0_1() { return cCasillasCasillaEStringParserRuleCall_4_2_0_1; }
		
		//(',' casillas+=[Casilla|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//','
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//casillas+=[Casilla|EString]
		public Assignment getCasillasAssignment_4_3_1() { return cCasillasAssignment_4_3_1; }
		
		//[Casilla|EString]
		public CrossReference getCasillasCasillaCrossReference_4_3_1_0() { return cCasillasCasillaCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getCasillasCasillaEStringParserRuleCall_4_3_1_0_1() { return cCasillasCasillaEStringParserRuleCall_4_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
	}
	public class MostrarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Mostrar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMostrarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEtiquetaAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEtiquetaEStringParserRuleCall_1_0 = (RuleCall)cEtiquetaAssignment_1.eContents().get(0);
		private final Keyword cDiciendoKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMensajeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMensajeEStringParserRuleCall_3_0 = (RuleCall)cMensajeAssignment_3.eContents().get(0);
		
		//Mostrar:
		//	'Mostrar:' etiqueta=EString 'diciendo' mensaje=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'Mostrar:' etiqueta=EString 'diciendo' mensaje=EString
		public Group getGroup() { return cGroup; }
		
		//'Mostrar:'
		public Keyword getMostrarKeyword_0() { return cMostrarKeyword_0; }
		
		//etiqueta=EString
		public Assignment getEtiquetaAssignment_1() { return cEtiquetaAssignment_1; }
		
		//EString
		public RuleCall getEtiquetaEStringParserRuleCall_1_0() { return cEtiquetaEStringParserRuleCall_1_0; }
		
		//'diciendo'
		public Keyword getDiciendoKeyword_2() { return cDiciendoKeyword_2; }
		
		//mensaje=EString
		public Assignment getMensajeAssignment_3() { return cMensajeAssignment_3; }
		
		//EString
		public RuleCall getMensajeEStringParserRuleCall_3_0() { return cMensajeEStringParserRuleCall_3_0; }
	}
	public class CerrarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Cerrar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCerrarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEtiquetaAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEtiquetaEStringParserRuleCall_1_0 = (RuleCall)cEtiquetaAssignment_1.eContents().get(0);
		
		//Cerrar:
		//	'Cerrar:' etiqueta=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'Cerrar:' etiqueta=EString
		public Group getGroup() { return cGroup; }
		
		//'Cerrar:'
		public Keyword getCerrarKeyword_0() { return cCerrarKeyword_0; }
		
		//etiqueta=EString
		public Assignment getEtiquetaAssignment_1() { return cEtiquetaAssignment_1; }
		
		//EString
		public RuleCall getEtiquetaEStringParserRuleCall_1_0() { return cEtiquetaEStringParserRuleCall_1_0; }
	}
	
	
	private final WizardElements pWizard;
	private final BotonElements pBoton;
	private final EStringElements pEString;
	private final PaginaElements pPagina;
	private final EBooleanElements pEBoolean;
	private final CampoElements pCampo;
	private final CasillaElements pCasilla;
	private final NavegarElements pNavegar;
	private final MostrarElements pMostrar;
	private final CerrarElements pCerrar;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public WizardGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pWizard = new WizardElements();
		this.pBoton = new BotonElements();
		this.pEString = new EStringElements();
		this.pPagina = new PaginaElements();
		this.pEBoolean = new EBooleanElements();
		this.pCampo = new CampoElements();
		this.pCasilla = new CasillaElements();
		this.pNavegar = new NavegarElements();
		this.pMostrar = new MostrarElements();
		this.pCerrar = new CerrarElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("wizard.Wizard".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Wizard:
	//	'Wizard' titulo=EString ':'
	//	paginas+=Pagina paginas+=Pagina*;
	public WizardElements getWizardAccess() {
		return pWizard;
	}
	
	public ParserRule getWizardRule() {
		return getWizardAccess().getRule();
	}
	
	//Boton:
	//	Navegar | Mostrar | Cerrar;
	public BotonElements getBotonAccess() {
		return pBoton;
	}
	
	public ParserRule getBotonRule() {
		return getBotonAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Pagina:
	//	'Pagina' (inicial?='inicial' name=EString | name=EString) ':' ((campos+=Campo campos+=Campo*)? (casillas+=Casilla
	//	casillas+=Casilla*)? botones+=Boton botones+=Boton*);
	public PaginaElements getPaginaAccess() {
		return pPagina;
	}
	
	public ParserRule getPaginaRule() {
		return getPaginaAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//Campo:
	//	'Campo' obligatorio?='obligatorio'? ':' etiqueta=EString;
	public CampoElements getCampoAccess() {
		return pCampo;
	}
	
	public ParserRule getCampoRule() {
		return getCampoAccess().getRule();
	}
	
	//Casilla:
	//	'Casilla' seleccionado?='seleccionada'? name=EString ':' etiqueta=EString ('destino' nuevoDestino=[Pagina|EString])?;
	public CasillaElements getCasillaAccess() {
		return pCasilla;
	}
	
	public ParserRule getCasillaRule() {
		return getCasillaAccess().getRule();
	}
	
	//Navegar:
	//	'Navegar' ':' etiqueta=EString destino=[Pagina|EString] ('dependencias' '{' casillas+=[Casilla|EString] (','
	//	casillas+=[Casilla|EString])* '}')?;
	public NavegarElements getNavegarAccess() {
		return pNavegar;
	}
	
	public ParserRule getNavegarRule() {
		return getNavegarAccess().getRule();
	}
	
	//Mostrar:
	//	'Mostrar:' etiqueta=EString 'diciendo' mensaje=EString;
	public MostrarElements getMostrarAccess() {
		return pMostrar;
	}
	
	public ParserRule getMostrarRule() {
		return getMostrarAccess().getRule();
	}
	
	//Cerrar:
	//	'Cerrar:' etiqueta=EString;
	public CerrarElements getCerrarAccess() {
		return pCerrar;
	}
	
	public ParserRule getCerrarRule() {
		return getCerrarAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
