/*
 * generated by Xtext 2.21.0
 */
package wizard.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWizardScopeProvider extends DelegatingScopeProvider {
}
